/**
 * Active-tasks board renderer (P1 fleet — Liveness / "never go dead").
 *
 * The vault's `agent-shared/active-tasks.md` is the cross-agent coordination
 * board. Its original updater was a cron-injected agent PROMPT that died — the
 * file has been frozen on the `_will be auto-populated_` placeholder since
 * 2026-05-07, so agents lost shared visibility into who is doing what (a root
 * cause of the duplicate-work incidents).
 *
 * This module replaces that dead prompt with a deterministic TS renderer: it
 * turns the live bus task list into the board markdown. The
 * `VaultLivenessWatchdog` calls `writeActiveTasksBoard` on an interval so the
 * board can never go stale again — every cycle it is rewritten from the bus.
 *
 * `renderActiveTasksBoard` is pure (tasks + timestamp in, markdown out) so it is
 * fully unit-testable without touching the filesystem or the clock.
 */

import { join } from 'path';
import type { Task } from '../types/index.js';
import { atomicWriteSync, ensureDir } from '../utils/atomic.js';

/** Vault-relative path of the auto-regenerated cross-agent board. */
export const ACTIVE_TASKS_REL = join('agent-shared', 'active-tasks.md');
/** Vault-relative path of the human/agent-authored narrative state (never auto-written, only watched). */
export const PROJECT_STATE_REL = join('agent-shared', 'project-state.md');
/** The dead-updater placeholder this renderer exists to eliminate. */
export const PLACEHOLDER = '_will be auto-populated_';

const PRIORITY_RANK: Record<string, number> = { urgent: 0, high: 1, normal: 2, low: 3 };

/** Make a task title safe to drop into a single markdown table cell. */
function cell(text: string): string {
  return (text || '').replace(/\r?\n/g, ' ').replace(/\|/g, '\\|').trim() || '—';
}

function sortForBoard(a: Task, b: Task): number {
  const pa = PRIORITY_RANK[a.priority] ?? 9;
  const pb = PRIORITY_RANK[b.priority] ?? 9;
  if (pa !== pb) return pa - pb;
  // Most recently touched first within a priority band.
  return (b.updated_at || '').localeCompare(a.updated_at || '');
}

function table(tasks: Task[], dateField: 'updated_at' | 'created_at'): string {
  const header = dateField === 'created_at'
    ? '| ID | Agent | Priority | Title | Created |'
    : '| ID | Agent | Priority | Title | Updated |';
  const sep = '|---|---|---|---|---|';
  if (tasks.length === 0) {
    return `${header}\n${sep}\n| _none_ |  |  |  |  |`;
  }
  const rows = tasks.map((t) => {
    const bundle = (t as { bundle_id?: string }).bundle_id;
    const title = bundle ? `${cell(t.title)} _(bundle: ${cell(bundle)})_` : cell(t.title);
    const when = (t[dateField] || '').replace('T', ' ').replace(/\..*$/, '');
    return `| ${cell(t.id)} | ${cell(t.assigned_to)} | ${t.priority} | ${title} | ${when} |`;
  });
  return [header, sep, ...rows].join('\n');
}

/**
 * Render the cross-agent active-tasks board markdown from the live task list.
 * Pure: no filesystem, no clock — `renderedAt` is supplied by the caller.
 */
export function renderActiveTasksBoard(tasks: Task[], renderedAt: string): string {
  const live = tasks.filter((t) => !t.archived);
  const inProgress = live.filter((t) => t.status === 'in_progress').sort(sortForBoard);
  const open = live.filter((t) => t.status === 'pending').sort(sortForBoard);
  const blocked = live.filter((t) => t.status === 'blocked').sort(sortForBoard);

  const total = inProgress.length + open.length + blocked.length;

  return [
    '---',
    'type: active-tasks',
    'agent: agent-shared',
    'tags: [agent-shared, active-tasks, fleet-wide]',
    `generated: ${renderedAt}`,
    '---',
    '',
    '# Active Tasks Board (Cross-Agent)',
    '',
    `> Auto-regenerated by the cortextos vault-liveness-watchdog — do not edit by hand.`,
    `> Last render: ${renderedAt} · ${total} active (${inProgress.length} in-progress, ${open.length} open, ${blocked.length} blocked).`,
    '',
    '## Currently in-progress',
    table(inProgress, 'updated_at'),
    '',
    '## Open (waiting pickup)',
    table(open, 'created_at'),
    '',
    '## Blocked (dependency not yet complete)',
    table(blocked, 'updated_at'),
    '',
  ].join('\n');
}

/**
 * Render and atomically write the board to `<vaultRoot>/agent-shared/active-tasks.md`.
 * Returns the absolute path written.
 */
export function writeActiveTasksBoard(vaultRoot: string, tasks: Task[], renderedAt: string): string {
  const out = join(vaultRoot, ACTIVE_TASKS_REL);
  ensureDir(join(vaultRoot, 'agent-shared'));
  atomicWriteSync(out, renderActiveTasksBoard(tasks, renderedAt));
  return out;
}
